### ISSUE TITLE
AttributeError with zpython after 154fe12

### ISSUE THREAD

**Issue by Lokaltog** [powerline/powerline#360]
I admit that I should have tested this further (the tests didn't fail and I couldn't see anything wrong so I assumed it was safe to merge), and I just noticed this error after opening a new terminal window:

```
Traceback (most recent call last):                                                                                                                                                    
  File "/home/kim/powerline/powerline/bindings/zsh/__init__.py", line 58, in __str__
    return self.render(width=zsh.columns(), side=self.side).encode('utf-8')
  File "/home/kim/powerline/powerline/renderer.py", line 67, in render
    segments = [self.get_highlighting(segment, mode) for segment in segments
  File "/home/kim/powerline/powerline/theme.py", line 76, in get_segments
    contents = segment['contents_func'](segment_info=segment_info, **segment['args'])
  File "/home/kim/powerline/powerline/segments/shell.py", line 23, in last_pipe_status
    if any(segment_info.last_pipe_status):
AttributeError: 'NoneType' object has no attribute 'last_pipe_status'
zsh: Failed to create string object for parameter ZPYTHON_POWERLINE_RPS1
```

The error was introduced in 154fe12.
